title: Nanoseconds Hunter
description: "kcrt's web site."
url: "https://www.kcrt.net/"
author:
  name: TAKAHASHI, Kyohei
  email: kcrt@kcrt.net
markdown: kramdown
kramdown:
  input: GFM
timezone: Asia/Tokyo
livereload: true
exclude:
  - no_git
gems:
  - jekyll-sitemap
permalink: /:categories/:title
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: pages
  -
    scope:
      path: ""
      type: posts
    values:
      permalink: /:categories/:year/:month/:day/:title
      layout: pages
